---
version: '2'
services:
  app:
    build: .
    ports:
      - 4000
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - db
    environment:
      VIRTUAL_PORT: 4000
      VIRTUAL_HOST: inno_test.local
  db:
    image: postgres:10
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword

volumes:
  postgres:
    driver: local
